---
title: "FOIA dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    #source_code: embed
    theme:
      version: 4
      bootswatch: lux
---

```{r global}
library(flexdashboard)
library(shiny)
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyr)
library(ggplot2)
library(stringr)

# global variables
rda_dir <- "data/rda"
agencies <- c("DHS", "EPA", "DOL", "DOJ", "DOS", "HHS")
component_list <- list(
  "DHS" = c("CBP", "PRIV", "USCIS", "ICE", "OIG", "CRCL"),
  "EPA" = c("HQ", "Region 1", "Region 2", "Region 3",
            "Region 4", "Region 5", "Region 6", "Region 7",
            "Region 8", "Region 9", "Region 10"),
  "DOL" = c("OSHA", "WHD", "OSEC", "OIG"),
  "DOJ" = c("EOIR", "OIG"),
  "HHS" = c("CDC", "ACF", "OIG"),
  "DOS" = c("OIG", "DoS")
)

# load functions used in script
source("functions.R")
source("ui_functions.R")
```

Pending Requests
=====================================

Inputs {.sidebar}
-------------------------------------

<br>
<br>
<br>

The dashboard displays the data from the Freedom of Information Act (FOIA) Annual Reports released each year by federal agencies and their components. The sources for the department and component annual budgets data are available [here](https://www.justice.gov/oip/reports-1). The sections of the Annual Reports are accessible via the top panel. 

Please select data type, component agency(s), and fiscal year(s) below. 

```{r}
selectInput("PendingRAgency", "Agency", choices = c("DHS", "EPA", "DOL", "DOJ", "DOS", "HHS"), selected = c("DHS"))

pending_choices <- c("Simple Pending Requests" = "SimplePendingRequestStatisticsPendingRequestQuantity",
                            "Simple Median Days" = "SimplePendingRequestStatisticsPendingRequestMedianDaysValue",
                            "Simple Average Days" ="SimplePendingRequestStatisticsPendingRequestAverageDaysValue",
                            "Complex Pending Requests" = "ComplexPendingRequestStatisticsPendingRequestQuantity",
                            "Complex Median Days" = "ComplexPendingRequestStatisticsPendingRequestMedianDaysValue",
                     "Complex Average Days" = "ComplexPendingRequestStatisticsPendingRequestAverageDaysValue",
                     "Expedited Pending Requests" = "ExpeditedPendingRequestStatisticsPendingRequestQuantity",
                     "Expedited Median Days" = "ExpeditedPendingRequestStatisticsPendingRequestMedianDaysValue",
                     "Expedited Average Days" = "ExpeditedPendingRequestStatisticsPendingRequestAverageDaysValue")

selectInput("PendingRData", "Statistic", choices = pending_choices, selected = c("Simple Pending Requests"))

conditionalPanel(
  condition = "input.PendingRAgency == 'DHS'",
  checkboxGroupInput("PendingRComponentDHS", "Component", choices = c("CBP", "PRIV", "USCIS", "ICE", "OIG", "CRCL"), selected = c("CBP", "PRIV", "USCIS"))
)

conditionalPanel(
  condition = "input.PendingRAgency == 'EPA'",
  checkboxGroupInput("PendingRComponentEPA", "Component", choices = c("HQ", "Region 1", "Region 2", "Region 3", "Region 4", "Region 5", "Region 6", "Region 7", "Region 8", "Region 9", "Region 10"), selected = c("HQ"))
)

conditionalPanel(
  condition = "input.PendingRAgency == 'DOL'",
  checkboxGroupInput("PendingRComponentDOL", "Component", choices = c("OSHA", "WHD", "OSEC", "OIG"), selected = c("OIG", "OSHA"))
)

conditionalPanel(
  condition = "input.PendingRAgency == 'DOJ'",
  checkboxGroupInput("PendingRComponentDOJ", "Component", choices = c("EOIR", "OIG"), selected = c("EOIR"))
)

conditionalPanel(
  condition = "input.PendingRAgency == 'HHS'", 
  checkboxGroupInput("PendingRComponentHHS", "Component", choices = c("CDC", "ACF", "OIG"), selected = c("CDC"))
)

conditionalPanel(
  condition = "input.PendingRAgency == 'DOS'", 
  checkboxGroupInput("PendingRComponentDOS", "Component", choices = c("OIG", "DoS"), selected = c("OIG"))
)

checkboxGroupInput("PendingRFY", "FY", choices = c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"), selected = c("10", "11", "12", "13", "14", "15", "16", "17", "18"))

```

<br/>
For more information about the FOIA, see [foia.gov](https://www.foia.gov).

<br/><br/>
Created by [Kendall McKay](https://deportation-research.buffett.northwestern.edu/people/) for the [Deportation Research Clinic](https://deportation-research.buffett.northwestern.edu).
<br>
<br>
<br>
Project support provided by [Aaron Geller](https://faculty.wcas.northwestern.edu/aaron-geller/) and [Patrick Zacher](https://www.linkedin.com/in/patrick-zacher/) of Northwestern University's [IT Research Computing and Data Services (RCDS)](https://www.it.northwestern.edu/departments/it-services-support/research/).
<br>
<br>
<br>
Funding provided by the Northwestern University [Institute for Policy Research (IPR)](https://www.ipr.northwestern.edu).

Row {data-height=300}
-------------------------------------

###

```{r}
filtered_data_pendingR <- reactive({
  if (input$PendingRAgency == "DHS") {
    load("DHS_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  } else if (input$PendingRAgency == "EPA") {
    load("EPA_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  } else if (input$PendingRAgency == "DOL") {
    load("DOL_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  } else if (input$PendingRAgency == "DOJ") {
    load("DOJ_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  } else if (input$PendingRAgency == "HHS") {
    load("HHS_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  } else if (input$PendingRAgency == "DOS") {
    load("DOS_PPR_data.Rda")
    return(foia_data$PendingPerfectedRequestsSection)
  }
})

filtered_input_pendingR_component <- reactive({
  if (input$PendingRAgency == "DHS") {
    return(input$PendingRComponentDHS)
  } else if (input$PendingRAgency == "EPA") {
    return(input$PendingRComponentEPA)
  } else if (input$PendingRAgency == "DOL") {
    return(input$PendingRComponentDOL)
  } else if (input$PendingRAgency == "DOJ") {
    return(input$PendingRComponentDOJ)
  } else if (input$PendingRAgency == "HHS") {
    return(input$PendingRComponentHHS)
  } else if (input$PendingRAgency == "DOS") {
    return(input$PendingRComponentDOS)}
})

## not sure how to get the median, average, and 

filtered_input_pendingR_statistics <- reactive({
  if (input$PendingRData == "SimplePendingRequestStatistics") {
    return(foia_data$PendingPerfectedRequestsSection$SimplePendingRequestStatistics)
  } else if (input$PendingRData == "ComplexPendingRequestStatistics") {
    return(foia_data$PendingPerfectedRequestsSection$ComplexPendingRequestStatistics)
  } else if (input$PendingRData == "ExpeditedPendingRequestStatistics") {
    return(foia_data$PendingPerfectedRequestsSection$ExpeditedPendingRequestStatistics)
  }
})

filtered_input_manual_title_pendingR <- reactive({
  if (input$PendingRData == "SimplePendingRequestStatisticsPendingRequestQuantity") {
    return("Simple Pending Request Quantity")
  } else if (input$PendingRData == "SimplePendingRequestStatisticsPendingRequestMedianDaysValue") {
    return("Simple Pending Request Median Days")
  } else if (input$PendingRData == "SimplePendingRequestStatisticsPendingRequestAverageDaysValue") {
    return("Simple Pending Request Average Days")
  } else if (input$PendingRData == "ComplexPendingRequestStatisticsPendingRequestQuantity") {
    return("Complex Pending Request Quantity")
  } else if (input$PendingRData == "ComplexPendingRequestStatisticsPendingRequestMedianDaysValue") {
    return("Complex Pending Request Median Days")
  } else if (input$PendingRData == "ComplexPendingRequestStatisticsPendingRequestAverageDaysValue") {
    return("Complex Pending Request Average Days")
  } else if (input$PendingRData == "ExpeditedPendingRequestStatisticsPendingRequestQuantity") {
    return("Expedited Pending Request Quantity")
  } else if (input$PendingRData == "ExpeditedPendingRequestStatisticsPendingRequestMedianDaysValue") {
    return("Expedited Pending Request Median Days")
  } else if (input$PendingRData == "ExpeditedPendingRequestStatisticsPendingRequestAverageDaysValue") {
    return("Expedited Pending Request Average Days")
  } else {
    return(NULL)  # Return NULL if no match is found
  }
})

#observeEvent(input$BacklogData, {print(input$BacklogData)})

#observeEvent(input$BacklogComponent, {print(input$BacklogComponent)})

#renderTable(filtered_data_backlog())

renderPlotly({
  plot_single_column(filtered_data_pendingR(), input$PendingRData, filtered_input_pendingR_component(),  input$PendingRFY, manual_titles = filtered_input_manual_title_pendingR())
})
```